/** Accent palette used across portfolio surfaces. */
export const AccentTone = {
  Rose: 'rose',
  Cosmic: 'cosmic',
  Amber: 'amber',
  Forest: 'forest',
} as const

export type AccentTone = (typeof AccentTone)[keyof typeof AccentTone]

/** Shared facet tags for wall panels, rails, honor stats, and hero facts. */
export const ContentTag = {
  Platform: 'platform',
  Infra: 'infra',
  Docker: 'docker',
  Traefik: 'traefik',
  Tls: 'tls',
  ControlPlane: 'controlPlane',
  Fastapi: 'fastapi',
  React: 'react',
  Kafka: 'kafka',
  Crawl: 'crawl',
  Mcp: 'mcp',
  Analytics: 'analytics',
  Auth: 'auth',
  Iam: 'iam',
  Go: 'go',
  Fiber: 'fiber',
  Grpc: 'grpc',
  Flutter: 'flutter',
  Material3: 'material3',
  Mobile: 'mobile',
  Fpga: 'fpga',
  DigitalDesign: 'digitalDesign',
  Hardware: 'hardware',
  Cpen: 'cpen',
  Mediapipe: 'mediapipe',
  Python: 'python',
  Java: 'java',
  Enterprise: 'enterprise',
  Rest: 'rest',
  Capstone: 'capstone',
  Mechatronics: 'mechatronics',
  Creative: 'creative',
  Gsap: 'gsap',
  ThisSite: 'thisSite',
  ObjectStorage: 'objectStorage',
  S3: 's3',
  Docs: 'docs',
  Dx: 'dx',
  Runbooks: 'runbooks',
  Cv: 'cv',
  Ml: 'ml',
  Security: 'security',
  Realtime: 'realtime',
  CrossPlatform: 'crossPlatform',
  PrivateInfra: 'privateInfra',
  Repos16Plus: 'repos16Plus',
  Repos12Plus: 'repos12Plus',
  Verilog: 'verilog',
  OneTerm: 'oneTerm',
  Beijing: 'beijing',
  Summer2024: 'summer2024',
  English: 'english',
  Chinese: 'chinese',
  French: 'french',
  Graduating2027: 'graduating2027',
  NewGrad: 'newGrad',
  UbcAppliedScience: 'ubcAppliedScience',
  Year2024_2025: 'year2024_2025',
  HardwareFirmware: 'hardwareFirmware',
  CreativeWeb: 'creativeWeb',
  GradWindow2027: 'gradWindow2027',
  ComputerEngineering: 'computerEngineering',
  Ubc: 'ubc',
  Year4Senior: 'year4Senior',
  VancouverBc: 'vancouverBc',
} as const

export type ContentTag = (typeof ContentTag)[keyof typeof ContentTag]
